
print("Esta es una prueba")
print("Esta es otra prueba")
print("Esta es la última prueba")
print("Esta es una prueba")
print("Esta es otra prueba")
print("Esta es la última prueba")
print("Esta es una prueba")
print("Esta es otra prueba")
print("Esta es la última prueba")
print("Esta es una prueba")
print("Esta es otra prueba")
print("Esta es la última prueba")